name: edu
description: Practice Questions!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.3.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  go_router: ^14.8.1
  flutter_markdown: ^0.7.6+2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
